#+title: Dockerize microsoft Teams
#+author: Virgile Daugé

* Pré-requis

- Testé sous Linux. (pop!_os 20.04)
- docker https://docs.docker.com/engine/install/ubuntu/

* Usage

! Ne support pas encore les webcams !
#+BEGIN_SRC bash
docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/snd/ virgiletn/teams-for-linux
#+END_SRC

Il est bien évidemment possible de créer un alias pour plus de simplicité :

#+BEGIN_SRC bash
echo 'alias teams="docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/snd/ virgiletn/teams-for-linux"' >> ~/.bashrc
#+END_SRC

!! teams-for-linux ne gére pas les signaux système, il n'est donc pas
  possible en l'état de quitter proprement le container... !!
#+RESULTS:


* Pourquoi
Le nombre de réunions à explosé en raison du confinement et nombre de
réunions/soutenances sont (déraisonnablement?) proposées sous l'outil
Microsoft Teams.

Or, il n'est pas possible de l'utiliser correctement sous Firefox, il
est nécessaire d'installer le client lourd.

Bien qu'il existe une version Linux officielle, je tiens à garder pour
moi l'ensemble des données présentes sur ma machine.

C'est pourquoi j'ai bricolé de quoi lancer
"teams-for-linux" dans un container docker.

teams-for-linux est un client teams non officiel dispo ici :
https://github.com/IsmaelMartinez/teams-for-linux

* Dockerfile

#+BEGIN_SRC dockerfile :tangle ./dockerfile
FROM ubuntu:20.04

ENV VERSION 1.0.4
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y wget gdebi

RUN wget https://github.com/IsmaelMartinez/teams-for-linux/releases/download/v${VERSION}/teams-for-linux_${VERSION}_amd64.deb

RUN gdebi --non-interactive teams-for-linux_${VERSION}_amd64.deb

RUN useradd -m teams
RUN usermod -a -G audio teams
USER teams
ENTRYPOINT [ "teams-for-linux" ]
#+END_SRC
